name: urbanedge
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nomkl
  - pip
  - numpy<2.0
  - pandas
  - matplotlib
  - plotly
  - fpdf2
  - streamlit==1.51.0
  - pytorch
  - prophet==1.1.5
  - pip:
      - kaleido