name: urbanedge
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.51.0
      - pandas
      - plotly
      - kaleido
      - fpdf2
      - matplotlib
      - prophet>=1.2  # Upgrade to version compatible with Python 3.11
      - numpy<2.0
      - cmdstanpy>=1.3
