name: urbanedge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.51.0
      - pandas
      - plotly
      - kaleido
      - fpdf2
      - matplotlib
      - prophet==1.1.5
      - numpy<2.0
      - cmdstanpy==1.3.0
  - conda-forge::cmdstan  