name: urbanedge
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.51.0
      - pandas
      - plotly
      - kaleido
      - fpdf2
      - matplotlib
      - prophet==1.1.1
      - numpy<2.0
